const ELIGIBILITY_SERVICE_OUTPUT = Object.freeze({
    CUSTOMER_ELIGIBLE: Symbol('CUSTOMER_ELIGIBLE'),
    CUSTOMER_INELIGIBLE: Symbol('CUSTOMER_INELIGIBLE')
})

export default ELIGIBILITY_SERVICE_OUTPUT
