const REWARDS = Object.freeze({
    CHAMPIONS_LEAGUE_FINAL_TICKET: 'CHAMPIONS_LEAGUE_FINAL_TICKET',
    KARAOKE_PRO_MICROPHONE: 'KARAOKE_PRO_MICROPHONE',
    PIRATES_OF_THE_CARIBBEAN_COLLECTION: 'PIRATES_OF_THE_CARIBBEAN_COLLECTION'
})

export default REWARDS
