const REWARDS = Object.freeze({
  CHAMPIONS_LEAGUE_FINAL_TICKET: Symbol('CHAMPIONS_LEAGUE_FINAL_TICKET'),
  KARAOKE_PRO_MICROPHONE: Symbol('KARAOKE_PRO_MICROPHONE'),
  PIRATES_OF_THE_CARIBBEAN_COLLECTION: Symbol('PIRATES_OF_THE_CARIBBEAN_COLLECTION')
})

export default REWARDS
